# =============================================================================
# SPATIAL PHASE 2: MERGE GPS CLUSTERS WITH MASTER DATA
# =============================================================================
# Purpose: Extract coordinates from downloaded DHS Geographic datasets and
#          merge them with the standardized Bangladesh Master Dataset.
# Output:  Bangladesh_Spatial_Master.rds (Includes LATNUM, LONGNUM)
# =============================================================================

library(dplyr)
library(here)
library(rdhs)
library(sf)

cat("========================================\n")
cat("SPATIAL PHASE 2: GPS MERGE (BANGLADESH)\n")
cat("========================================\n\n")

# Set directories
base_dir <- here::here()
spatial_dir <- file.path(base_dir, "datasets", "spatial_gps")
results_dir <- file.path(base_dir, "results")

# 1. LOAD MASTER DATA
cat("Loading Bangladesh Master Dataset...\n")
master_file <- file.path(results_dir, "MASTER_IMPUTED_STANDARD_DATA.rds")
if(!file.exists(master_file)) stop("Master dataset not found!")

df_master <- readRDS(master_file)
cat("✔ Master Data loaded: N =", nrow(df_master), "\n\n")

# Read the locally cached GPS files directly to bypass DHS API authentication
gps_files <- list.files(file.path(spatial_dir, "datasets"), pattern = "\\.rds$", full.names = TRUE)
if(length(gps_files) == 0) stop("No GPS files found. Ensure SPATIAL_01 has been run.")
cat("Found", length(gps_files), "locally cached GPS files.\n")

# 3. EXTRACT AND BIND GPS COORDINATES
cat("Extracting Latitude and Longitude from Cached GPS Files...\n")

all_gps_data <- data.frame()

# We loop through the downloaded files and extract Cluster, Lat, Long
for (file_path in gps_files) {
  # Read the flat RDS file generated by rdhs
  gps_dat <- readRDS(file_path)
  
  # Select only the relevant spatial columns
  if(all(c("DHSCLUST", "LATNUM", "LONGNUM", "DHSYEAR") %in% names(gps_dat))) {
    clean_gps <- gps_dat %>%
      select(
        cluster_id = DHSCLUST,
        LATNUM,
        LONGNUM,
        year = DHSYEAR
      ) %>%
      # Ensure 0.0 coordinates (missing/ocean) are marked as NA
      mutate(
        LATNUM = ifelse(LATNUM == 0, NA, LATNUM),
        LONGNUM = ifelse(LONGNUM == 0, NA, LONGNUM)
      )
    
    all_gps_data <- bind_rows(all_gps_data, clean_gps)
  }
}

# Fix years to match our master string labels
all_gps_data <- all_gps_data %>%
  mutate(
    year_label = case_when(
      year == 2004 ~ "2004",
      year == 2011 ~ "2011",
      year == 2017 ~ "2017-2018",
      year == 2018 ~ "2017-2018",
      year == 2022 ~ "2022",
      TRUE ~ as.character(year)
    )
  )

# 4. MERGE WITH MASTER
cat("Merging GPS coordinates into Master Data...\n")
df_spatial <- df_master %>%
  left_join(
    all_gps_data %>% select(cluster_id, year_label, LATNUM, LONGNUM) %>% distinct(),
    by = c("cluster_id" = "cluster_id", "year_label" = "year_label")
  )

# Check missingness
missing_gps <- sum(is.na(df_spatial$LATNUM))
cat("✔ Merge complete.\n")
cat("  Total Records:", nrow(df_spatial), "\n")
cat("  Records with GPS:", nrow(df_spatial) - missing_gps, "\n")
cat("  Records missing GPS:", missing_gps, "\n\n")

# 5. CONVERT TO SIMPLE FEATURES (SF) OBJECT
# Coordinate Reference System 4326 is standard WGS84 (GPS)
cat("Converting to Spatial Features (sf) object...\n")
df_spatial_sf <- df_spatial %>%
  filter(!is.na(LATNUM) & !is.na(LONGNUM)) %>%
  st_as_sf(coords = c("LONGNUM", "LATNUM"), crs = 4326, remove = FALSE)

# 6. EXPORT
out_file <- file.path(results_dir, "Bangladesh_Spatial_Master.rds")
saveRDS(df_spatial_sf, out_file)

cat("========================================\n")
cat("SPATIAL PHASE 2 COMPLETE\n")
cat("========================================\n")
cat("Saved spatially-enabled dataset to:\n")
cat("  ", out_file, "\n")
cat("This dataset is now ready for Malaria Atlas travel-time extraction.\n")
